In [1]:
#Q1)
import numpy as np

# Create a 1D array with 5 elements
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)

# a) Addition of 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply 3 with all elements
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
#Q2)
import numpy as np

# a) Reverse the array
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])


# b) Find most frequent value and its indices

# i. Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
max_count = np.max(counts)

print("\nFor array x:")
print("Most frequent value(s):", values[counts == max_count])

for value in values[counts == max_count]:
    print("Value", value, "indices:", np.where(x == value)[0])


# ii. Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
max_count = np.max(counts)

print("\nFor array y:")
print("Most frequent value(s):", values[counts == max_count])

for value in values[counts == max_count]:
    print("Value", value, "indices:", np.where(y == value)[0])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]

For array x:
Most frequent value(s): [1]
Value 1 indices: [0 5 7 8 9]

For array y:
Most frequent value(s): [1 3]
Value 1 indices: [0 1 2]
Value 3 indices: [4 8 9]


In [3]:
#Q3)
import numpy as np

# Create 2-D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# a) Access 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
#Q4)
import numpy as np

# Create 1-D array with 25 evenly spaced numbers from 10 to 100
Harseerat = np.linspace(10, 100, 25)

print("Array:")
print(Harseerat)

# Array information
print("Dimensions:", Harseerat.ndim)
print("Shape:", Harseerat.shape)
print("Total elements:", Harseerat.size)
print("Data type:", Harseerat.dtype)
print("Total bytes:", Harseerat.nbytes)

# Transpose using reshape()
transpose = Harseerat.reshape(5, 5).T

print("\nTranspose using reshape():")
print(transpose)

# Transpose using T attribute
print("\nTranspose using T:")
print(Harseerat.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]

Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
#Q5)
import numpy as np

# Create 1-D NumPy array with 25 evenly spaced numbers from 10 to 100
Harseerat = np.linspace(10, 100, 25)

print("Array:")
print(Harseerat)

# Print array information
print("Dimensions:", Harseerat.ndim)
print("Shape:", Harseerat.shape)
print("Total elements:", Harseerat.size)
print("Data type:", Harseerat.dtype)
print("Total bytes:", Harseerat.nbytes)

# Transpose using reshape()
transpose = Harseerat.reshape(5, 5).T

print("\nTranspose using reshape():")
print(transpose)

# Transpose using T attribute
transpose_T = Harseerat.reshape(5, 5).T

print("\nTranspose using T attribute:")
print(transpose_T)


Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]

Transpose using T attribute:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
